source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

workspace 'MoPub-RFM Sample.xcworkspace'
xcodeproj 'MoPub-RFM Sample.xcodeproj'

target 'MoPub-RFM Sample' do
	pod 'mopub-ios-sdk'
	pod 'ColorUtils', '~> 1.1'
	pod 'iOS-Color-Picker', '~> 1.1'
	pod 'SVProgressHUD', '~> 1.1'
	pod 'CocoaLumberjack’, '~> 2.3.0’
	pod 'RFMAdSDK', '~> 6.0.0’
        pod 'RFMSDKAdapter-iOS-MoPub', '~> 3.0.0’
	pod 'OHHTTPStubs', '~> 4.8.0'
end
